language: ruby
rvm:
  - 2.3.0
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
before_install: gem install bundler -v 1.11.2
